import { Injectable } from '@angular/core';
import { Product } from '../models/product';

@Injectable({
  providedIn: 'root'
})
export class ProductService {
  
  products: Product[] = [
    new Product(1, 'GIÀY ADIDAS ULTRABOOST X LEGO® COLORS', 5000000, 'Chạy bộ chính là lúc để bạn chơi đùa. Với những điểm nhấn sắc màu và các khối LEGO®, đôi giày chạy bộ adidas hợp tác thiết kế cùng LEGO Group này sẽ cùng bạn thỏa sức chơi đùa. Vừa chơi đùa lại vừa thoải mái. Đừng để điều gì ảnh hưởng tới trải nghiệm vui thích của bạn. Đế giữa Boost êm ái nâng niu bàn chân, cùng đế ngoài bằng cao su Continental™ Better Rubber vừa mang đến những sải bước nhanh nhạy vừa đảm bảo khả năng tiếp đất ổn định.', 'Cloud White / Red / Shock Blue / Green', [3.5, 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 12.5], 'https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/6a0d6246e26a4852825dad3900baddfd_9366/Giay_adidas_Ultraboost_x_LEGO(r)_Colors_trang_FZ3983_01_standard.jpg', 'No returns, no refunds', 'Đơn hàng được xác nhận sau khi xác nhận thanh toán. Không đổi hàng, trả hàng hay hoàn tiền trừ trường hợp pháp luật có quy định khác. Sản phẩm này không áp dụng bất kỳ chương trình ưu đãi và khuyến mãi nào. Giới hạn số lượng 1 sản phẩm trên mỗi đơn hàng.'),
    new Product(2, 'GIÀY ADIDAS SUPERSTAR X LEGO®', 2500000, 'Đam mê, quan điểm và ý tưởng của bạn là những gì khiến bạn trở nên khác biệt. Khi bạn tìm thấy cho mình tinh thần sáng tạo và biểu đạt bản thân, đôi giày adidas này cũng hòa quyện các màu sắc cơ bản và pastel vào từng sải bước. Khi cất lên tiếng nói là bạn tạo ra cơ hội để cộng đồng của mình thêm lớn mạnh. Logo Ba Lá như lời nhắc về sức mạnh của tình đoàn kết.<br><br>Sản phẩm này có sử dụng chất liệu tái chế, là một phần cam kết của chúng tôi hướng tới chấm dứt rác thải nhựa. 20% thân giày làm từ chất liệu có chứa tối thiểu 50% thành phần tái chế.', 'Cloud White / Halo Mint / Core Black', [3.5, 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9], 'https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/f64a0e3176364556aa83ad220006023a_9366/Giay_Forum_Low_trang_GZ9112_01_standard.jpg'),
    new Product(3, 'GIÀY FORUM LOW', 2500000, 'Đam mê, quan điểm và ý tưởng của bạn là những gì khiến bạn trở nên khác biệt. Khi bạn tìm thấy cho mình tinh thần sáng tạo và biểu đạt bản thân, đôi giày adidas này cũng hòa quyện các màu sắc cơ bản và pastel vào từng sải bước. Khi cất lên tiếng nói là bạn tạo ra cơ hội để cộng đồng của mình thêm lớn mạnh. Logo Ba Lá như lời nhắc về sức mạnh của tình đoàn kết.<br><br>Sản phẩm này có sử dụng chất liệu tái chế, là một phần cam kết của chúng tôi hướng tới chấm dứt rác thải nhựa. 20% thân giày làm từ chất liệu có chứa tối thiểu 50% thành phần tái chế.', 'Cloud White / Legend Ink / Red', [3.5, 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12, 13], 'https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/985c3fb92ba8432e9433ad220016f0b3_9366/Giay_Forum_Low_trang_H01678_01_standard.jpg'),
    new Product(4, 'GIÀY ADIDAS ULTRABOOST DNA X LEGO® COLORS', 5000000, 'Chạy bộ chính là lúc để bạn chơi đùa. Với những điểm nhấn sắc màu và các khối LEGO®, đôi giày chạy bộ adidas hợp tác thiết kế cùng LEGO Group này sẽ cùng bạn thỏa sức chơi đùa. Vừa chơi đùa lại vừa thoải mái. Đừng để điều gì ảnh hưởng tới trải nghiệm vui thích của bạn. Đế giữa Boost êm ái nâng niu bàn chân, cùng đế ngoài bằng cao su Continental™ Better Rubber vừa mang đến những sải bước nhanh nhạy vừa đảm bảo khả năng tiếp đất ổn định.', 'Cloud White / Shock Blue / Cloud White', [6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11], 'https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/b22f9d0d3fd54d279acbad1d00b4ddc5_9366/Giay_adidas_Ultraboost_DNA_x_LEGO(r)_Colors_trang_H67952_01_standard.jpg', 'No returns, no refunds', 'Đơn hàng được xác nhận sau khi xác nhận thanh toán. Không đổi hàng, trả hàng hay hoàn tiền trừ trường hợp pháp luật có quy định khác. Sản phẩm này không áp dụng bất kỳ chương trình ưu đãi và khuyến mãi nào. Giới hạn số lượng 1 sản phẩm trên mỗi đơn hàng.'),
    new Product(5, 'GIÀY ADIDAS ULTRABOOST DNA X LEGO® COLORS', 5000000, 'Chạy bộ chính là lúc để bạn chơi đùa. Với những điểm nhấn sắc màu và các khối LEGO®, đôi giày chạy bộ adidas hợp tác thiết kế cùng LEGO Group này sẽ cùng bạn thỏa sức chơi đùa. Vừa chơi đùa lại vừa thoải mái. Đừng để điều gì ảnh hưởng tới trải nghiệm vui thích của bạn. Đế giữa Boost êm ái nâng niu bàn chân, cùng đế ngoài bằng cao su Continental™ Better Rubber vừa mang đến những sải bước nhanh nhạy vừa đảm bảo khả năng tiếp đất ổn định.', 'Cloud White / Red / Cloud White', [3.5, 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 12.5], 'https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/60712c4ffd24452fbe87acee00dbf61a_9366/gi%C3%A0y-adidas-ultraboost-dna-x-lego-colors.jpg', 'No returns, no refunds', 'Đơn hàng được xác nhận sau khi xác nhận thanh toán. Không đổi hàng, trả hàng hay hoàn tiền trừ trường hợp pháp luật có quy định khác. Sản phẩm này không áp dụng bất kỳ chương trình ưu đãi và khuyến mãi nào. Giới hạn số lượng 1 sản phẩm trên mỗi đơn hàng.'),
    new Product(6, 'GIÀY ĐÁ BÓNG SÂN CỎ NHÂN TẠO X SPEEDFLOW.4', 1900000, 'Dưới ánh đèn ngập tràn nơi sân tập và trên sân đấu, bạn vẫn có cách ẩn mình trong bóng tối. Bắt nhịp trận đấu chỉ với một cú chạm. Hãy mang đôi giày adidas Copa Sense để tập trung vào bản năng bóng đá của bạn. Đôi giày đá bóng này giúp giảm thiểu phân tâm nhờ cổ giày co giãn có thể kéo rộng ra để xỏ chân dễ dàng. Mũi giày bằng da mềm mại thích ứng theo hình dáng bàn chân, tăng cường sự chắc chắn cho từng cú chạm bóng. Lớp đệm EVA mềm mại giúp bạn thi triển chiến thuật khó lường.<br><br>Sản phẩm này có sử dụng chất liệu tái chế, là một phần quyết tâm của chúng tôi hướng tới chấm dứt rác thải nhựa. 20% thân giày làm từ chất liệu có chứa tối thiểu 50% thành phần tái chế.', 'Core Black / Sonic Ink / Solar Yellow', [3.5, 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 10, 10.5, 11, 11.5, 12, 13], 'https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/98f9d4638422489b9bbbacc2010cab0f_9366/gi%C3%A0y-%C4%91%C3%A1-b%C3%B3ng-s%C3%A2n-c%E1%BB%8F-nh%C3%A2n-t%E1%BA%A1o-x-speedflow.3.jpg'),
    ]

  constructor() { }

  getProduct(): Product[] {
    return this.products;
  }
}
