import { Injectable } from '@angular/core';
import { Product } from '../models/product';

@Injectable({
  providedIn: 'root'
})
export class ProductService {

  products: Product[] = [
    new Product(1, 'GIÀY ADIDAS ULTRABOOST X LEGO® COLORS', 5000000, 'Chạy bộ chính là lúc để bạn chơi đùa. Với những điểm nhấn sắc màu và các khối LEGO®, đôi giày chạy bộ adidas hợp tác thiết kế cùng LEGO Group này sẽ cùng bạn thỏa sức chơi đùa. Vừa chơi đùa lại vừa thoải mái. Đừng để điều gì ảnh hưởng tới trải nghiệm vui thích của bạn. Đế giữa Boost êm ái nâng niu bàn chân, cùng đế ngoài bằng cao su Continental™ Better Rubber vừa mang đến những sải bước nhanh nhạy vừa đảm bảo khả năng tiếp đất ổn định.', 'Cloud White / Red / Shock Blue / Green', 3.5, 'https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/6a0d6246e26a4852825dad3900baddfd_9366/Giay_adidas_Ultraboost_x_LEGO(r)_Colors_trang_FZ3983_01_standard.jpg', 'No returns, no refunds', 'Đơn hàng được xác nhận sau khi xác nhận thanh toán. Không đổi hàng, trả hàng hay hoàn tiền trừ trường hợp pháp luật có quy định khác. Sản phẩm này không áp dụng bất kỳ chương trình ưu đãi và khuyến mãi nào. Giới hạn số lượng 1 sản phẩm trên mỗi đơn hàng.'),
    new Product(1, 'GIÀY ADIDAS ULTRABOOST X LEGO® COLORS', 5000000, 'Chạy bộ chính là lúc để bạn chơi đùa. Với những điểm nhấn sắc màu và các khối LEGO®, đôi giày chạy bộ adidas hợp tác thiết kế cùng LEGO Group này sẽ cùng bạn thỏa sức chơi đùa. Vừa chơi đùa lại vừa thoải mái. Đừng để điều gì ảnh hưởng tới trải nghiệm vui thích của bạn. Đế giữa Boost êm ái nâng niu bàn chân, cùng đế ngoài bằng cao su Continental™ Better Rubber vừa mang đến những sải bước nhanh nhạy vừa đảm bảo khả năng tiếp đất ổn định.', 'Cloud White / Red / Shock Blue / Green', 3.5, 'https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/6a0d6246e26a4852825dad3900baddfd_9366/Giay_adidas_Ultraboost_x_LEGO(r)_Colors_trang_FZ3983_01_standard.jpg', 'No returns, no refunds', 'Đơn hàng được xác nhận sau khi xác nhận thanh toán. Không đổi hàng, trả hàng hay hoàn tiền trừ trường hợp pháp luật có quy định khác. Sản phẩm này không áp dụng bất kỳ chương trình ưu đãi và khuyến mãi nào. Giới hạn số lượng 1 sản phẩm trên mỗi đơn hàng.'),
    new Product(1, 'GIÀY ADIDAS ULTRABOOST X LEGO® COLORS', 5000000, 'Chạy bộ chính là lúc để bạn chơi đùa. Với những điểm nhấn sắc màu và các khối LEGO®, đôi giày chạy bộ adidas hợp tác thiết kế cùng LEGO Group này sẽ cùng bạn thỏa sức chơi đùa. Vừa chơi đùa lại vừa thoải mái. Đừng để điều gì ảnh hưởng tới trải nghiệm vui thích của bạn. Đế giữa Boost êm ái nâng niu bàn chân, cùng đế ngoài bằng cao su Continental™ Better Rubber vừa mang đến những sải bước nhanh nhạy vừa đảm bảo khả năng tiếp đất ổn định.', 'Cloud White / Red / Shock Blue / Green', 3.5, 'https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/6a0d6246e26a4852825dad3900baddfd_9366/Giay_adidas_Ultraboost_x_LEGO(r)_Colors_trang_FZ3983_01_standard.jpg', 'No returns, no refunds', 'Đơn hàng được xác nhận sau khi xác nhận thanh toán. Không đổi hàng, trả hàng hay hoàn tiền trừ trường hợp pháp luật có quy định khác. Sản phẩm này không áp dụng bất kỳ chương trình ưu đãi và khuyến mãi nào. Giới hạn số lượng 1 sản phẩm trên mỗi đơn hàng.'),
    new Product(2, 'giay a', 100, 'This is giay a', 'red', 6, 'https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/f64a0e3176364556aa83ad220006023a_9366/Giay_Forum_Low_trang_GZ9112_01_standard.jpg'),
    new Product(3, 'giay b', 200, 'This is giay b', 'red', 5, 'https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/985c3fb92ba8432e9433ad220016f0b3_9366/Giay_Forum_Low_trang_H01678_01_standard.jpg'),
    new Product(4, 'giay c', 150, 'This is giay c', 'red', 4.5, 'https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/b22f9d0d3fd54d279acbad1d00b4ddc5_9366/Giay_adidas_Ultraboost_DNA_x_LEGO(r)_Colors_trang_H67952_01_standard.jpg'),
    new Product(5, 'giay d', 100, 'This is giay d', 'red', 3, 'https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/60712c4ffd24452fbe87acee00dbf61a_9366/gi%C3%A0y-adidas-ultraboost-dna-x-lego-colors.jpg'),
    new Product(6, 'giay e', 100, 'This is giay e', 'red', 3, 'https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/98f9d4638422489b9bbbacc2010cab0f_9366/gi%C3%A0y-%C4%91%C3%A1-b%C3%B3ng-s%C3%A2n-c%E1%BB%8F-nh%C3%A2n-t%E1%BA%A1o-x-speedflow.3.jpg'),
    new Product(1, 'GIÀY ADIDAS ULTRABOOST X LEGO® COLORS', 5000000, 'Chạy bộ chính là lúc để bạn chơi đùa. Với những điểm nhấn sắc màu và các khối LEGO®, đôi giày chạy bộ adidas hợp tác thiết kế cùng LEGO Group này sẽ cùng bạn thỏa sức chơi đùa. Vừa chơi đùa lại vừa thoải mái. Đừng để điều gì ảnh hưởng tới trải nghiệm vui thích của bạn. Đế giữa Boost êm ái nâng niu bàn chân, cùng đế ngoài bằng cao su Continental™ Better Rubber vừa mang đến những sải bước nhanh nhạy vừa đảm bảo khả năng tiếp đất ổn định.', 'Cloud White / Red / Shock Blue / Green', 3.5, 'https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/6a0d6246e26a4852825dad3900baddfd_9366/Giay_adidas_Ultraboost_x_LEGO(r)_Colors_trang_FZ3983_01_standard.jpg', 'No returns, no refunds', 'Đơn hàng được xác nhận sau khi xác nhận thanh toán. Không đổi hàng, trả hàng hay hoàn tiền trừ trường hợp pháp luật có quy định khác. Sản phẩm này không áp dụng bất kỳ chương trình ưu đãi và khuyến mãi nào. Giới hạn số lượng 1 sản phẩm trên mỗi đơn hàng.'),
    new Product(1, 'GIÀY ADIDAS ULTRABOOST X LEGO® COLORS', 5000000, 'Chạy bộ chính là lúc để bạn chơi đùa. Với những điểm nhấn sắc màu và các khối LEGO®, đôi giày chạy bộ adidas hợp tác thiết kế cùng LEGO Group này sẽ cùng bạn thỏa sức chơi đùa. Vừa chơi đùa lại vừa thoải mái. Đừng để điều gì ảnh hưởng tới trải nghiệm vui thích của bạn. Đế giữa Boost êm ái nâng niu bàn chân, cùng đế ngoài bằng cao su Continental™ Better Rubber vừa mang đến những sải bước nhanh nhạy vừa đảm bảo khả năng tiếp đất ổn định.', 'Cloud White / Red / Shock Blue / Green', 3.5, 'https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/6a0d6246e26a4852825dad3900baddfd_9366/Giay_adidas_Ultraboost_x_LEGO(r)_Colors_trang_FZ3983_01_standard.jpg', 'No returns, no refunds', 'Đơn hàng được xác nhận sau khi xác nhận thanh toán. Không đổi hàng, trả hàng hay hoàn tiền trừ trường hợp pháp luật có quy định khác. Sản phẩm này không áp dụng bất kỳ chương trình ưu đãi và khuyến mãi nào. Giới hạn số lượng 1 sản phẩm trên mỗi đơn hàng.'),
    new Product(1, 'GIÀY ADIDAS ULTRABOOST X LEGO® COLORS', 5000000, 'Chạy bộ chính là lúc để bạn chơi đùa. Với những điểm nhấn sắc màu và các khối LEGO®, đôi giày chạy bộ adidas hợp tác thiết kế cùng LEGO Group này sẽ cùng bạn thỏa sức chơi đùa. Vừa chơi đùa lại vừa thoải mái. Đừng để điều gì ảnh hưởng tới trải nghiệm vui thích của bạn. Đế giữa Boost êm ái nâng niu bàn chân, cùng đế ngoài bằng cao su Continental™ Better Rubber vừa mang đến những sải bước nhanh nhạy vừa đảm bảo khả năng tiếp đất ổn định.', 'Cloud White / Red / Shock Blue / Green', 3.5, 'https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/6a0d6246e26a4852825dad3900baddfd_9366/Giay_adidas_Ultraboost_x_LEGO(r)_Colors_trang_FZ3983_01_standard.jpg', 'No returns, no refunds', 'Đơn hàng được xác nhận sau khi xác nhận thanh toán. Không đổi hàng, trả hàng hay hoàn tiền trừ trường hợp pháp luật có quy định khác. Sản phẩm này không áp dụng bất kỳ chương trình ưu đãi và khuyến mãi nào. Giới hạn số lượng 1 sản phẩm trên mỗi đơn hàng.'),
    new Product(1, 'GIÀY ADIDAS ULTRABOOST X LEGO® COLORS', 5000000, 'Chạy bộ chính là lúc để bạn chơi đùa. Với những điểm nhấn sắc màu và các khối LEGO®, đôi giày chạy bộ adidas hợp tác thiết kế cùng LEGO Group này sẽ cùng bạn thỏa sức chơi đùa. Vừa chơi đùa lại vừa thoải mái. Đừng để điều gì ảnh hưởng tới trải nghiệm vui thích của bạn. Đế giữa Boost êm ái nâng niu bàn chân, cùng đế ngoài bằng cao su Continental™ Better Rubber vừa mang đến những sải bước nhanh nhạy vừa đảm bảo khả năng tiếp đất ổn định.', 'Cloud White / Red / Shock Blue / Green', 3.5, 'https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/6a0d6246e26a4852825dad3900baddfd_9366/Giay_adidas_Ultraboost_x_LEGO(r)_Colors_trang_FZ3983_01_standard.jpg', 'No returns, no refunds', 'Đơn hàng được xác nhận sau khi xác nhận thanh toán. Không đổi hàng, trả hàng hay hoàn tiền trừ trường hợp pháp luật có quy định khác. Sản phẩm này không áp dụng bất kỳ chương trình ưu đãi và khuyến mãi nào. Giới hạn số lượng 1 sản phẩm trên mỗi đơn hàng.'),
    new Product(1, 'GIÀY ADIDAS ULTRABOOST X LEGO® COLORS', 5000000, 'Chạy bộ chính là lúc để bạn chơi đùa. Với những điểm nhấn sắc màu và các khối LEGO®, đôi giày chạy bộ adidas hợp tác thiết kế cùng LEGO Group này sẽ cùng bạn thỏa sức chơi đùa. Vừa chơi đùa lại vừa thoải mái. Đừng để điều gì ảnh hưởng tới trải nghiệm vui thích của bạn. Đế giữa Boost êm ái nâng niu bàn chân, cùng đế ngoài bằng cao su Continental™ Better Rubber vừa mang đến những sải bước nhanh nhạy vừa đảm bảo khả năng tiếp đất ổn định.', 'Cloud White / Red / Shock Blue / Green', 3.5, 'https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy,c_fill,g_auto/6a0d6246e26a4852825dad3900baddfd_9366/Giay_adidas_Ultraboost_x_LEGO(r)_Colors_trang_FZ3983_01_standard.jpg', 'No returns, no refunds', 'Đơn hàng được xác nhận sau khi xác nhận thanh toán. Không đổi hàng, trả hàng hay hoàn tiền trừ trường hợp pháp luật có quy định khác. Sản phẩm này không áp dụng bất kỳ chương trình ưu đãi và khuyến mãi nào. Giới hạn số lượng 1 sản phẩm trên mỗi đơn hàng.'),
  ]

  constructor() { }

  getProduct(): Product[] {
    return this.products;
  }
}
